from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True, slots=True)
class ToolDoc:
    tool_id: str
    group_id: str
    name: str
    compact: str
    usage: str
    example: str
    keywords: tuple[str, ...]


@dataclass(frozen=True, slots=True)
class ToolGroup:
    group_id: str
    name: str
    compact: str
    tool_ids: tuple[str, ...]
    keywords: tuple[str, ...]


TOOL_DOCS: tuple[ToolDoc, ...] = (
    ToolDoc(
        "file_search",
        "filesystem",
        "file_search",
        "find files by name",
        "query: filename or fragment",
        "file_search(query='README')",
        ("find file", "search file", "filename", "readme"),
    ),
    ToolDoc(
        "read_file",
        "filesystem",
        "read_file",
        "read text file",
        "path: relative file path",
        "read_file(path='README.md')",
        ("read file", "open file", "inspect file"),
    ),
    ToolDoc(
        "write_file",
        "filesystem",
        "write_file",
        "overwrite file",
        "path, content",
        "write_file(path='a.txt', content='hello')",
        ("write file", "overwrite file"),
    ),
    ToolDoc(
        "create_file",
        "filesystem",
        "create_file",
        "create new file",
        "path, content optional",
        "create_file(path='a.txt', content='hello')",
        ("create file", "new file"),
    ),
    ToolDoc(
        "append_file",
        "filesystem",
        "append_file",
        "append text",
        "path, content",
        "append_file(path='a.txt', content='\nmore')",
        ("append file", "append text"),
    ),
    ToolDoc(
        "apply_patch",
        "filesystem",
        "apply_patch",
        "replace exact text",
        "path, old_text, new_text",
        "apply_patch(path='a.txt', old_text='x', new_text='y')",
        ("patch file", "replace text", "apply patch"),
    ),
    ToolDoc(
        "delete_file",
        "filesystem",
        "delete_file",
        "delete file or dir",
        "path",
        "delete_file(path='old.txt')",
        ("delete file", "remove file"),
    ),
    ToolDoc(
        "move_file",
        "filesystem",
        "move_file",
        "move or rename path",
        "source, destination",
        "move_file(source='a.txt', destination='b.txt')",
        ("move file", "rename file"),
    ),
    ToolDoc(
        "copy_file",
        "filesystem",
        "copy_file",
        "copy file",
        "source, destination",
        "copy_file(source='a.txt', destination='b.txt')",
        ("copy file", "duplicate file"),
    ),
    ToolDoc(
        "list_directory",
        "filesystem",
        "list_directory",
        "list directory entries",
        "path optional, default '.'",
        "list_directory(path='.')",
        ("list directory", "list files", "workspace", "files here"),
    ),
    ToolDoc(
        "get_file_info",
        "filesystem",
        "get_file_info",
        "stat path",
        "path",
        "get_file_info(path='a.txt')",
        ("file info", "stat file", "timestamps"),
    ),
    ToolDoc(
        "tree_view",
        "filesystem",
        "tree_view",
        "recursive structure",
        "path optional, max_depth optional",
        "tree_view(path='.', max_depth=3)",
        (
            "tree",
            "recursive structure",
            "project structure",
            "codebase structure",
            "look around",
            "repo structure",
            "important files",
        ),
    ),
    ToolDoc(
        "grep_search",
        "dev",
        "grep_search",
        "search text in files",
        "query, path optional",
        "grep_search(query='router')",
        ("grep", "search text", "where is"),
    ),
    ToolDoc(
        "find_symbol",
        "dev",
        "find_symbol",
        "find class/function",
        "name, path optional",
        "find_symbol(name='ShowcaseService')",
        ("find symbol", "function", "class"),
    ),
    ToolDoc(
        "run_tests",
        "dev",
        "run_tests",
        "run test command",
        "command optional",
        "run_tests(command='pytest -q')",
        ("run tests", "pytest"),
    ),
    ToolDoc(
        "lint_code",
        "dev",
        "lint_code",
        "run lint command",
        "command optional",
        "lint_code(command='ruff check .')",
        ("lint", "lint code"),
    ),
    ToolDoc(
        "format_code",
        "dev",
        "format_code",
        "run format command",
        "command optional",
        "format_code(command='ruff format .')",
        ("format", "format code"),
    ),
    ToolDoc(
        "execute_script",
        "dev",
        "execute_script",
        "run script file",
        "path, args optional",
        "execute_script(path='script.py')",
        ("execute script", "run script"),
    ),
    ToolDoc(
        "build_project",
        "dev",
        "build_project",
        "run build command",
        "command optional",
        "build_project(command='python -m build')",
        ("build project", "build"),
    ),
    ToolDoc(
        "install_dependencies",
        "dev",
        "install_dependencies",
        "install deps",
        "command optional",
        "install_dependencies(command='pip install -e .')",
        ("install dependencies", "pip install"),
    ),
    ToolDoc(
        "git_status",
        "git",
        "git_status",
        "show repo status",
        "no args",
        "git_status()",
        ("git status", "repo status"),
    ),
    ToolDoc(
        "git_diff",
        "git",
        "git_diff",
        "show diff",
        "ref optional",
        "git_diff()",
        ("git diff", "show diff"),
    ),
    ToolDoc(
        "git_log",
        "git",
        "git_log",
        "show commit log",
        "limit optional",
        "git_log(limit=10)",
        ("git log", "commit history"),
    ),
    ToolDoc(
        "git_add",
        "git",
        "git_add",
        "stage paths",
        "paths optional",
        "git_add(paths=['file.txt'])",
        ("git add", "stage file"),
    ),
    ToolDoc(
        "git_commit",
        "git",
        "git_commit",
        "create commit",
        "message",
        "git_commit(message='add feature')",
        ("git commit", "commit"),
    ),
    ToolDoc(
        "git_checkout",
        "git",
        "git_checkout",
        "switch branch/ref",
        "target, create optional",
        "git_checkout(target='feature')",
        ("git checkout", "switch branch"),
    ),
    ToolDoc(
        "git_branch",
        "git",
        "git_branch",
        "list or create branch",
        "name optional, create optional",
        "git_branch(name='feature', create=True)",
        ("git branch", "create branch"),
    ),
    ToolDoc(
        "git_merge",
        "git",
        "git_merge",
        "merge target",
        "target",
        "git_merge(target='feature')",
        ("git merge", "merge branch"),
    ),
    ToolDoc(
        "git_reset",
        "git",
        "git_reset",
        "reset ref",
        "target, confirm for risky",
        "git_reset(target='--soft HEAD~1')",
        ("git reset", "reset commit"),
    ),
    ToolDoc(
        "git_stash",
        "git",
        "git_stash",
        "stash changes",
        "action optional",
        "git_stash(action='push')",
        ("git stash", "stash"),
    ),
    ToolDoc(
        "shell_command",
        "system",
        "shell_command",
        "guarded shell",
        "command, confirm if risky",
        "shell_command(command='pwd')",
        ("shell command", "run command"),
    ),
    ToolDoc(
        "safe_shell_command",
        "system",
        "safe_shell_command",
        "restricted shell",
        "command without shell metacharacters",
        "safe_shell_command(command='pwd')",
        ("safe shell", "restricted shell"),
    ),
    ToolDoc(
        "process_list",
        "system",
        "process_list",
        "list processes",
        "no args",
        "process_list()",
        ("process list", "ps"),
    ),
    ToolDoc(
        "kill_process",
        "system",
        "kill_process",
        "kill pid",
        "pid, confirm",
        "kill_process(pid=123, confirm=True)",
        ("kill process", "terminate pid"),
    ),
    ToolDoc(
        "system_info",
        "system",
        "system_info",
        "cpu ram disk os",
        "no args",
        "system_info()",
        ("system info", "cpu", "disk", "os"),
    ),
    ToolDoc(
        "env_vars",
        "system",
        "env_vars",
        "read env vars",
        "prefix optional",
        "env_vars(prefix='PATH')",
        ("env vars", "environment"),
    ),
    ToolDoc(
        "web_search",
        "web",
        "web_search",
        "search web",
        "query",
        "web_search(query='ollama json schema')",
        ("web search", "search web", "look up"),
    ),
    ToolDoc(
        "expand_search_result",
        "web",
        "expand_search_result",
        "expand one result",
        "url, query optional",
        "expand_search_result(url='https://example.com', query='topic')",
        ("expand result", "open result", "read result"),
    ),
    ToolDoc(
        "expand_search_results",
        "web",
        "expand_search_results",
        "expand top search hits",
        "query, limit optional",
        "expand_search_results(query='latest linux kernel', limit=3)",
        ("expand search", "expand results", "deeper search"),
    ),
    ToolDoc(
        "fetch_url",
        "web",
        "fetch_url",
        "fetch URL body",
        "url",
        "fetch_url(url='https://example.com')",
        ("fetch url", "download html"),
    ),
    ToolDoc(
        "extract_webpage_content",
        "web",
        "extract_webpage_content",
        "html to text",
        "url or html",
        "extract_webpage_content(url='https://example.com')",
        ("extract webpage", "clean html"),
    ),
    ToolDoc(
        "download_file",
        "web",
        "download_file",
        "download file",
        "url, destination",
        "download_file(url='https://x', destination='x.bin')",
        ("download file", "fetch file"),
    ),
    ToolDoc(
        "parse_pdf",
        "web",
        "parse_pdf",
        "extract pdf text",
        "path",
        "parse_pdf(path='examples/assets/sample.pdf')",
        ("parse pdf", "pdf text"),
    ),
    ToolDoc(
        "parse_json_api",
        "web",
        "parse_json_api",
        "fetch + parse json",
        "url",
        "parse_json_api(url='https://api.example.com')",
        ("json api", "parse json"),
    ),
    ToolDoc(
        "weather_lookup",
        "web",
        "weather_lookup",
        "current weather/forecast",
        "query or location/at_time",
        "weather_lookup(query='weather in London tomorrow at 3pm')",
        ("weather", "forecast", "temperature"),
    ),
    ToolDoc(
        "latest_linux_kernel",
        "web",
        "latest_linux_kernel",
        "current kernel releases",
        "no args",
        "latest_linux_kernel()",
        ("latest linux kernel", "kernel version", "stable kernel"),
    ),
    ToolDoc(
        "screenshot_page",
        "web",
        "screenshot_page",
        "render page snapshot",
        "url",
        "screenshot_page(url='https://example.com')",
        ("screenshot page", "page snapshot"),
    ),
    ToolDoc(
        "build_index",
        "retrieval",
        "build_index",
        "index text files",
        "path optional",
        "build_index(path='.')",
        ("build index", "index project"),
    ),
    ToolDoc(
        "query_index",
        "retrieval",
        "query_index",
        "search index",
        "query",
        "query_index(query='routing')",
        ("query index", "search index"),
    ),
    ToolDoc(
        "update_index",
        "retrieval",
        "update_index",
        "rebuild index",
        "path optional",
        "update_index(path='.')",
        ("update index", "refresh index"),
    ),
    ToolDoc(
        "delete_from_index",
        "retrieval",
        "delete_from_index",
        "remove source",
        "source",
        "delete_from_index(source='README.md')",
        ("delete from index", "remove indexed source"),
    ),
    ToolDoc(
        "list_indexed_sources",
        "retrieval",
        "list_indexed_sources",
        "list indexed docs",
        "no args",
        "list_indexed_sources()",
        ("list indexed sources", "indexed docs"),
    ),
    ToolDoc(
        "save_memory",
        "memory",
        "save_memory",
        "persist key/value",
        "key, value",
        "save_memory(key='color', value='blue')",
        ("save memory", "remember"),
    ),
    ToolDoc(
        "load_memory",
        "memory",
        "load_memory",
        "load memory",
        "key optional",
        "load_memory(key='color')",
        ("load memory", "recall"),
    ),
    ToolDoc(
        "update_memory",
        "memory",
        "update_memory",
        "update key/value",
        "key, value",
        "update_memory(key='color', value='green')",
        ("update memory", "change memory"),
    ),
    ToolDoc(
        "delete_memory",
        "memory",
        "delete_memory",
        "delete memory",
        "key",
        "delete_memory(key='color')",
        ("delete memory", "forget"),
    ),
    ToolDoc(
        "list_memories",
        "memory",
        "list_memories",
        "list memory keys",
        "no args",
        "list_memories()",
        ("list memories", "memory keys"),
    ),
    ToolDoc(
        "task_checkpoint",
        "memory",
        "task_checkpoint",
        "save task note",
        "task_id, note",
        "task_checkpoint(task_id='id', note='halfway')",
        ("task checkpoint", "checkpoint"),
    ),
    ToolDoc(
        "load_checkpoint",
        "memory",
        "load_checkpoint",
        "load checkpoint",
        "task_id",
        "load_checkpoint(task_id='id')",
        ("load checkpoint", "checkpoint state"),
    ),
    ToolDoc(
        "summarize_session",
        "memory",
        "summarize_session",
        "summarize recent events",
        "limit optional",
        "summarize_session(limit=20)",
        ("summarize session", "session summary"),
    ),
    ToolDoc(
        "plan_task",
        "task",
        "plan_task",
        "create task plan",
        "title, steps",
        "plan_task(title='demo', steps=['a', 'b'])",
        ("plan task", "task plan"),
    ),
    ToolDoc(
        "execute_step",
        "task",
        "execute_step",
        "mark step in progress",
        "task_id, step_index",
        "execute_step(task_id='id', step_index=0)",
        ("execute step", "task step"),
    ),
    ToolDoc(
        "mark_step_complete",
        "task",
        "mark_step_complete",
        "complete step",
        "task_id, step_index",
        "mark_step_complete(task_id='id', step_index=0)",
        ("complete step", "mark step complete"),
    ),
    ToolDoc(
        "retry_step",
        "task",
        "retry_step",
        "reset step",
        "task_id, step_index",
        "retry_step(task_id='id', step_index=1)",
        ("retry step", "rerun step"),
    ),
    ToolDoc(
        "abort_task",
        "task",
        "abort_task",
        "abort task",
        "task_id",
        "abort_task(task_id='id')",
        ("abort task", "cancel task"),
    ),
    ToolDoc(
        "get_task_status",
        "task",
        "get_task_status",
        "read task state",
        "task_id",
        "get_task_status(task_id='id')",
        ("task status", "get task status"),
    ),
    ToolDoc(
        "request_user_approval",
        "safety",
        "request_user_approval",
        "approval gate",
        "action, confirm optional",
        "request_user_approval(action='delete file')",
        ("request approval", "approval"),
    ),
    ToolDoc(
        "check_permission",
        "safety",
        "check_permission",
        "permission gate",
        "action, risky optional",
        "check_permission(action='git_reset', risky=True)",
        ("check permission", "permission"),
    ),
    ToolDoc(
        "log_sensitive_action",
        "safety",
        "log_sensitive_action",
        "log risky action",
        "action, details optional",
        "log_sensitive_action(action='git_reset')",
        ("log sensitive action", "audit"),
    ),
    ToolDoc(
        "sandbox_file_access",
        "safety",
        "sandbox_file_access",
        "validate path",
        "path",
        "sandbox_file_access(path='README.md')",
        ("sandbox file", "validate path"),
    ),
    ToolDoc(
        "sandbox_shell_execution",
        "safety",
        "sandbox_shell_execution",
        "validate shell command",
        "command",
        "sandbox_shell_execution(command='pwd')",
        ("sandbox shell", "validate shell"),
    ),
    ToolDoc(
        "log_event",
        "observability",
        "log_event",
        "append event",
        "event_type, payload optional",
        "log_event(event_type='demo')",
        ("log event", "event log"),
    ),
    ToolDoc(
        "trace_step",
        "observability",
        "trace_step",
        "trace task step",
        "task_id, step",
        "trace_step(task_id='id', step='demo')",
        ("trace step", "trace"),
    ),
    ToolDoc(
        "record_tool_latency",
        "observability",
        "record_tool_latency",
        "record latency",
        "tool_name, latency_ms",
        "record_tool_latency(tool_name='grep', latency_ms=12)",
        ("tool latency", "latency"),
    ),
    ToolDoc(
        "record_error",
        "observability",
        "record_error",
        "record error",
        "error, context optional",
        "record_error(error='boom')",
        ("record error", "error log"),
    ),
    ToolDoc(
        "replay_session",
        "observability",
        "replay_session",
        "show recent events",
        "limit optional",
        "replay_session(limit=20)",
        ("replay session", "session replay"),
    ),
    ToolDoc(
        "summarize_run",
        "observability",
        "summarize_run",
        "summarize current run",
        "limit optional",
        "summarize_run(limit=20)",
        ("summarize run", "run summary"),
    ),
    ToolDoc(
        "calculate",
        "utility",
        "calculate",
        "safe arithmetic",
        "expression",
        "calculate(expression='6 * 7')",
        ("calculate", "math"),
    ),
    ToolDoc(
        "datetime_now",
        "utility",
        "datetime_now",
        "current timestamp",
        "no args",
        "datetime_now()",
        ("datetime", "current time"),
    ),
    ToolDoc(
        "convert_units",
        "utility",
        "convert_units",
        "unit conversion",
        "value, from_unit, to_unit",
        "convert_units(value=2, from_unit='km', to_unit='m')",
        ("convert units", "unit conversion"),
    ),
    ToolDoc(
        "generate_uuid",
        "utility",
        "generate_uuid",
        "new uuid",
        "no args",
        "generate_uuid()",
        ("uuid", "generate uuid"),
    ),
    ToolDoc(
        "hash_file",
        "utility",
        "hash_file",
        "hash file",
        "path, algorithm optional",
        "hash_file(path='a.txt')",
        ("hash file", "checksum"),
    ),
    ToolDoc(
        "encode_decode",
        "utility",
        "encode_decode",
        "base64 encode/decode",
        "mode, data, encoding optional",
        "encode_decode(mode='encode', data='hello')",
        ("base64", "encode", "decode"),
    ),
    ToolDoc(
        "run_model",
        "optional",
        "run_model",
        "nested model call",
        "prompt",
        "run_model(prompt='summarize this')",
        ("run model", "nested model"),
    ),
    ToolDoc(
        "transcribe_audio",
        "optional",
        "transcribe_audio",
        "offline speech to text",
        "path",
        "transcribe_audio(path='examples/assets/speech.wav')",
        ("transcribe audio", "speech to text"),
    ),
    ToolDoc(
        "text_to_speech",
        "optional",
        "text_to_speech",
        "synthesize speech",
        "text, destination optional",
        "text_to_speech(text='hello', destination='examples/assets/speech-output.wav')",
        ("text to speech", "tts"),
    ),
    ToolDoc(
        "analyze_image",
        "optional",
        "analyze_image",
        "inspect image metadata",
        "path",
        "analyze_image(path='image.png')",
        ("analyze image", "image metadata"),
    ),
    ToolDoc(
        "control_device",
        "optional",
        "control_device",
        "record device command",
        "command",
        "control_device(command='turn lamp on')",
        ("device control", "iot"),
    ),
    ToolDoc(
        "adapter_inventory",
        "adapters",
        "adapter_inventory",
        "list source adapters",
        "no args",
        "adapter_inventory()",
        ("adapter inventory", "source projects", "provenance"),
    ),
)


TOOL_GROUPS: tuple[ToolGroup, ...] = (
    ToolGroup(
        "filesystem",
        "File",
        "search/read/write/patch/move/delete/info/tree",
        (
            "file_search",
            "read_file",
            "write_file",
            "create_file",
            "append_file",
            "apply_patch",
            "delete_file",
            "move_file",
            "copy_file",
            "list_directory",
            "get_file_info",
            "tree_view",
        ),
        ("file", "path", "directory", "tree"),
    ),
    ToolGroup(
        "dev",
        "Dev",
        "grep/symbols/tests/lint/format/scripts/build/install",
        (
            "grep_search",
            "find_symbol",
            "run_tests",
            "lint_code",
            "format_code",
            "execute_script",
            "build_project",
            "install_dependencies",
        ),
        ("test", "lint", "build", "script", "symbol"),
    ),
    ToolGroup(
        "git",
        "Git",
        "status/diff/log/add/commit/branch/checkout/merge/reset/stash",
        (
            "git_status",
            "git_diff",
            "git_log",
            "git_add",
            "git_commit",
            "git_checkout",
            "git_branch",
            "git_merge",
            "git_reset",
            "git_stash",
        ),
        ("git", "commit", "branch", "diff"),
    ),
    ToolGroup(
        "system",
        "System",
        "shell/processes/system/env",
        (
            "shell_command",
            "safe_shell_command",
            "process_list",
            "kill_process",
            "system_info",
            "env_vars",
        ),
        ("shell", "system", "process", "environment"),
    ),
    ToolGroup(
        "web",
        "Web",
        "search/fetch/extract/download/pdf/json/screenshot",
        (
            "web_search",
            "fetch_url",
            "extract_webpage_content",
            "download_file",
            "parse_pdf",
            "parse_json_api",
            "screenshot_page",
        ),
        ("web", "url", "html", "pdf", "json"),
    ),
    ToolGroup(
        "retrieval",
        "Retrieval",
        "build/query/update/delete/list index",
        (
            "build_index",
            "query_index",
            "update_index",
            "delete_from_index",
            "list_indexed_sources",
        ),
        ("index", "retrieval", "query index"),
    ),
    ToolGroup(
        "memory",
        "Memory",
        "save/load/update/delete/list/checkpoint/session",
        (
            "save_memory",
            "load_memory",
            "update_memory",
            "delete_memory",
            "list_memories",
            "task_checkpoint",
            "load_checkpoint",
            "summarize_session",
        ),
        ("memory", "checkpoint", "session"),
    ),
    ToolGroup(
        "task",
        "Task",
        "plan/execute/complete/retry/abort/status",
        (
            "plan_task",
            "execute_step",
            "mark_step_complete",
            "retry_step",
            "abort_task",
            "get_task_status",
        ),
        ("task", "plan", "step"),
    ),
    ToolGroup(
        "safety",
        "Safety",
        "approval/permission/audit/sandbox",
        (
            "request_user_approval",
            "check_permission",
            "log_sensitive_action",
            "sandbox_file_access",
            "sandbox_shell_execution",
        ),
        ("approval", "permission", "sandbox"),
    ),
    ToolGroup(
        "observability",
        "Obs",
        "events/trace/latency/errors/replay/summary",
        (
            "log_event",
            "trace_step",
            "record_tool_latency",
            "record_error",
            "replay_session",
            "summarize_run",
        ),
        ("log", "trace", "error", "summary"),
    ),
    ToolGroup(
        "utility",
        "Util",
        "math/time/convert/uuid/hash/base64",
        (
            "calculate",
            "datetime_now",
            "convert_units",
            "generate_uuid",
            "hash_file",
            "encode_decode",
        ),
        ("calculate", "convert", "uuid", "hash", "base64"),
    ),
    ToolGroup(
        "optional",
        "Optional",
        "model/audio/image/device",
        (
            "run_model",
            "transcribe_audio",
            "text_to_speech",
            "analyze_image",
            "control_device",
        ),
        ("model", "audio", "image", "device"),
    ),
    ToolGroup(
        "adapters",
        "Adapters",
        "source project inventory",
        ("adapter_inventory",),
        ("adapter", "provenance", "source project"),
    ),
)


TOOL_DOC_BY_ID = {doc.tool_id: doc for doc in TOOL_DOCS}
GROUP_BY_ID = {group.group_id: group for group in TOOL_GROUPS}


def render_tool_hierarchy() -> str:
    return "\n".join(f"- {group.name}: {group.compact}" for group in TOOL_GROUPS)


def render_tool_usage(tool_ids: list[str]) -> str:
    rows: list[str] = []
    seen: set[str] = set()
    for tool_id in tool_ids:
        doc = TOOL_DOC_BY_ID.get(tool_id)
        if doc is None or tool_id in seen:
            continue
        seen.add(tool_id)
        rows.append(
            f"- {doc.name}: {doc.compact}. Use: {doc.usage}. Example: {doc.example}"
        )
    return "\n".join(rows) if rows else "No detailed tool usage selected."


def render_group_usage(group_ids: list[str]) -> str:
    rows: list[str] = []
    seen: set[str] = set()
    for group_id in group_ids:
        group = GROUP_BY_ID.get(group_id)
        if group is None or group_id in seen:
            continue
        seen.add(group_id)
        preview = ", ".join(group.tool_ids[:6])
        suffix = " ..." if len(group.tool_ids) > 6 else ""
        rows.append(f"- {group.name}: {group.compact}. Tools: {preview}{suffix}")
    return "\n".join(rows) if rows else "No detailed tool groups selected."


def render_tool_docs(tool_ids: list[str]) -> str:
    return render_tool_usage(tool_ids)


def select_tool_docs(text: str, limit: int = 4) -> list[str]:
    lowered = text.lower()
    scored: list[tuple[int, str]] = []
    for doc in TOOL_DOCS:
        score = sum(1 for keyword in doc.keywords if keyword in lowered)
        if score > 0:
            scored.append((score, doc.tool_id))
    scored.sort(key=lambda item: (-item[0], item[1]))
    return [tool_id for _, tool_id in scored[:limit]]


def select_tool_groups(text: str, limit: int = 3) -> list[str]:
    lowered = text.lower()
    scored: list[tuple[int, str]] = []
    for group in TOOL_GROUPS:
        score = sum(1 for keyword in group.keywords if keyword in lowered)
        if score > 0:
            scored.append((score, group.group_id))
    scored.sort(key=lambda item: (-item[0], item[1]))
    return [group_id for _, group_id in scored[:limit]]


def tool_group_for(tool_id: str) -> str | None:
    doc = TOOL_DOC_BY_ID.get(tool_id)
    if doc is None:
        return None
    return doc.group_id
